<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 Synth.gltf
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  export const ref = new Group();

  const gltf = useGltf("/../../../../models/Synth.gltf");

  const component = forwardEventHandlers();
</script>

<T is={ref} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials.Case}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials["White Keys"]}
      position={[0, -0.01, 0.01]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube006.geometry}
      material={gltf.nodes.Cube006.material}
      position={[-0.19, 0.1, -0.07]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube003.geometry}
      material={gltf.materials.Knobs}
      position={[-0.14, 0.12, 0.37]}
      scale={[1, 0.41, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane.geometry}
      material={gltf.materials.Platform}
      position={[-0.14, 0.1, 0.37]}
      scale={1.2}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube004.geometry}
      material={gltf.materials["Material.002"]}
      position={[-0.14, 0.15, 0.37]}
      rotation={[0, 1.57, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube005.geometry}
      material={gltf.materials["Material.002"]}
      position={[-0.22, 0.11, 0.21]}
      scale={[0.41, 0.17, 0.41]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube002.geometry}
      material={gltf.materials.Platform}
      position={[0.14, 0.1, 0.39]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder.geometry}
      material={gltf.materials.Knobs}
      position={[0.14, -0.05, 0.37]}
      scale={1.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube011.geometry}
      material={gltf.materials.Knobs}
      position={[-0.17, 0.1, -0.07]}
      scale={[1, 1, 1.25]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube012.geometry}
      material={gltf.materials.Knobs}
      position={[-0.12, 0.1, -0.15]}
      scale={[1, 1, 1.25]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube013.geometry}
      material={gltf.materials.Knobs}
      position={[-0.18, 0.1, -0.23]}
      scale={[1, 1, 1.25]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube014.geometry}
      material={gltf.materials.Knobs}
      position={[-0.1, 0.1, -0.31]}
      scale={[1, 1, 1.25]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube015.geometry}
      material={gltf.materials.Platform}
      position={[-0.15, 0.1, -0.07]}
      scale={[1.08, 1, 1.29]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube016.geometry}
      material={gltf.materials.Platform}
      position={[-0.15, 0.1, -0.15]}
      scale={[1.08, 1, 1.29]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube017.geometry}
      material={gltf.materials.Platform}
      position={[-0.15, 0.1, -0.23]}
      scale={[1.08, 1, 1.29]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube018.geometry}
      material={gltf.materials.Platform}
      position={[-0.15, 0.1, -0.31]}
      scale={[1.08, 1, 1.29]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube007.geometry}
      material={gltf.materials["Black Keys"]}
      position={[0.1, 0.08, 0.17]}
      scale={[3.47, 1, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube008.geometry}
      material={gltf.materials["Black Keys"]}
      position={[0.1, 0.08, 0.07]}
      scale={[3.47, 1, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube009.geometry}
      material={gltf.materials["Black Keys"]}
      position={[0.1, 0.08, -0.04]}
      scale={[3.47, 1, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube010.geometry}
      material={gltf.materials["Black Keys"]}
      position={[0.1, 0.08, -0.24]}
      scale={[3.47, 1, 1]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
