<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 Terminal.gltf
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  export const ref = new Group();

  const gltf = useGltf("../../../../models/Terminal.gltf");

  const component = forwardEventHandlers();

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials["Material.005"]}
      position={[0, 1.11, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Text.geometry}
      material={gltf.materials["Material.003"]}
      position={[-0.79, 1.36, 0.02]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.86}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials["Material.004"]}
      position={[0, 1.11, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube002.geometry}
      material={gltf.materials["Material.004"]}
      position={[0, 1.11, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Text001.geometry}
      material={gltf.materials["Material.003"]}
      position={[-0.79, 1.36, 0.02]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.86}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
